monthly_income = input("Enter your monthly income: ")
monthly_expenses = input("Enter your total monthly expenses: ")
monthly_savings = int(monthly_income) - int(monthly_expenses)
print(f"Your monthly savings is: ${monthly_savings}.")
estimated_annual_savings = int(monthly_savings * 12 + (monthly_savings * 0.05))
print(f"Projected savings after one year, with interest,  is: ${estimated_annual_savings}.")